import React from "react";

const StartScreen = ({ onStart }) => {
  return (
    <div id="startScreen" className="screen active">
      <div className="welcome-card">
        <div className="game-description">
          <p>
            Describe the word without using any of the banned words - all
            generated by AI! Players take turns describing words while others
            try to guess. The describer can't use any of the banned words.
          </p>
        </div>

        <div className="instructions">
          <h3>
            <i className="fas fa-gamepad"></i> How to Play
          </h3>
          <div className="instruction-grid">
            <div className="instruction-item">
              <span className="instruction-icon">
                <i className="fas fa-users"></i>
              </span>
              <span>Players take turns describing words</span>
            </div>
            <div className="instruction-item">
              <span className="instruction-icon">
                <i className="fas fa-ban"></i>
              </span>
              <span>Can't use banned words or parts of the target word</span>
            </div>
            <div className="instruction-item">
              <span className="instruction-icon">
                <i className="fas fa-clock"></i>
              </span>
              <span>Custom time per round - get as many as you can!</span>
            </div>
            <div className="instruction-item">
              <span className="instruction-icon">
                <i className="fas fa-robot"></i>
              </span>
              <span>All words generated by AI</span>
            </div>
            <div className="instruction-item">
              <span className="instruction-icon">
                <i className="fas fa-undo"></i>
              </span>
              <span>Limited skips per round - use them wisely!</span>
            </div>
          </div>
        </div>

        <button
          id="startGameButton"
          className="btn btn-primary btn-large"
          onClick={onStart}
        >
          <i className="fas fa-play btn-icon"></i>
          Start Game
        </button>
      </div>
    </div>
  );
};

export default StartScreen;
